format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$terraform\
[]( bg:#06969A fg:#86BBD8)\
$docker_context\
[](bg:#3371E3 fg:#06969A)\
$kubernetes\
[]( bg:#33658A fg:#3371E3)\
$time\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E "
disabled = false # Disabled by default

[directory]
style = "bg:#DA627D fg:#EEEEEE "
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#EEEEEE "
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#FCA17D fg:#EEEEEE "
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#EEEEEE bg:#FCA17D"
conflicted = ' ${count}'
ahead = '﯁ ${count} '
behind = '﮾ ${count} '
diverged = ' | ﯁ ${ahead_count}  ﮾ ${behind_coun} '
untracked = ' ${count} '
stashed = ' ${count} '
modified = ' ${count} '
staged = ' ${count} '
renamed = ' ${count} '
deleted = ' ${count} '
format = '[$all_status$ahead_behind]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol ($version) ]($style)'

[terraform]
disabled = false
symbol = "行"
style = "bg:#86BBD8 fg:#EEEEEE "
format = '[ $symbol\($workspace\) ]($style)'
#format = '[[](fg:#86BBD8 bg:#06969A)$symbol\($workspace\)[](fg:#86BBD8 bg:#06969A)]($style)'
### uncomment the following, to see the version
# format = "[[](bg:#5836CD fg:#464347)$symbol$version($workspace)[](bg:#464347 fg:#5836CD)]($style)"

[kubernetes]
disabled = false
symbol = "☸︎"
style = "bg:#3371E3 fg:#EEEEEE "
format = '[ $symbol $context(\($namespace\)) ]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'


#       
